PokeApp/Models/ErrorViewModel.cs
namespace PokeApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PokeApp/Models/Pokemon.cs
namespace PokeApp.Models
{
    public class Pokemon
    {
        public string Name { get; set; }    
        public string Description { get; set; }

        public string Url { get; set; }

        public int Rating { get; set; } = 1;

        public int PokemonId { get; set; }

        public Pokemon(int ID,string desc, string url, int rate,string name)
        {
            Name = name;
            Description = desc; 
            Url = url;
            Rating = rate;
            PokemonId = ID;

        }

        
    }
    
}

PokeApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PokeApp.Models;
using System.Diagnostics;

namespace PokeApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PokeApp/Controllers/PokemonController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using PokeApp.Models;
using System.Text.Json;
using System.Linq;
namespace PokeApp.Controllers
{
    public class PokemonController : Controller
    {
        static List<int> allPokemons = Enumerable.Range(2, 1000).ToList();
        static int currentPokemon = 1;
        private static readonly HttpClient client = new HttpClient();
        static List<Pokemon> pokemons = new List<Pokemon>() { new Pokemon(1, "", "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/1.svg", 1, "bulbasaur") };
  
        public IActionResult Index()
        {

            Pokemon pokemon = pokemons.Find(p => p.PokemonId == currentPokemon);
           
            return View(pokemon);
        }

        public IActionResult Gallery()
        {
            return View(pokemons);
        }

        public IActionResult Pokedle()
        {

            Random random = new Random();
            int randomIndex = random.Next(pokemons.Count);
            return View(pokemons[randomIndex]);

        }
        [HttpPut] 
        public ActionResult UpdatePokemon(string argument,string pokeid)
        {
            int id = Int32.Parse(pokeid);
            int index = pokemons.FindIndex(a => a.PokemonId == id);
            pokemons[index].Rating = Int32.Parse(argument);
            currentPokemon= id; 
            return RedirectToAction("Index"); 
        }

        [HttpGet]
        public async Task<ActionResult> GetPokemon(string next, string pokeid)
        {

            int id = Int32.Parse(pokeid);
            int index = pokemons.FindIndex(a => a.PokemonId == id);
            int randomElement = id;
            if (next == "1")
            {
                if (index == pokemons.Count-1)
                {
                    Random random = new Random();
                    int randomIndex = random.Next(allPokemons.Count);
                    randomElement = allPokemons[randomIndex];
                    allPokemons.RemoveAt(randomIndex);
                    var response=await client.GetStringAsync("https://pokeapi.co/api/v2/pokemon/"+ randomElement);

                    dynamic data = JObject.Parse(response);
                    
                    
                    Pokemon newPok = new Pokemon(randomElement, "", data.sprites.other.dream_world.front_default.ToString(), 1, data.name.ToString());
                 
                    pokemons.Add(newPok);
                 

                }
                else
                {
                    randomElement = pokemons[index + 1].PokemonId;
                }
            }
            else
            {
                if(index != 0)
                {
                    randomElement = pokemons[index - 1].PokemonId;
                }
            }

            currentPokemon = randomElement;
            return RedirectToAction("Index");

        }

    }
}

PokeApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PokeApp/Views/Pokemon/Gallery.cshtml
@model List<Pokemon>
<link href="~/css/PokeStyle.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<h4 class="text-white">Oto galeria spotkanych przez Ciebie pokemonów!</h4>

@for (int i = 0; i < Model.Count() - 1; i += 3)
{
    <div class="row top30">
        @for (int j = 0; j < 3; j++)
        {
            @if (j == 0 || (Model.ElementAtOrDefault(i + j) != null))
            {
                <div class="col-md-4 mt-3">
                    <div class="card">
                        <div class="card-header">@Model.ElementAtOrDefault(i + j).Name</div>
                        <div class="card-body center justify-content-around">
                            <img class="gallery-img" src="@Model.ElementAtOrDefault(i + j).Url" alt="Picture Unavailable" />
                        </div>
                        <div class="card-footer rating-container">


                            <span  class="fa fa-star star" style="@(@Model.ElementAtOrDefault(i + j).Rating>=1 ? "color:orange" : "color:black")"></span>
                            <span  class="fa fa-star star" style="@(@Model.ElementAtOrDefault(i + j).Rating>=2 ? "color:orange" : "color:black")"></span>
                            <span  class="fa fa-star star" style="@(@Model.ElementAtOrDefault(i + j).Rating>=3 ? "color:orange" : "color:black")"></span>
                            <span  class="fa fa-star star" style="@(@Model.ElementAtOrDefault(i + j).Rating>=4 ? "color:orange" : "color:black")"></span>
                            <span  class="fa fa-star star" style="@(@Model.ElementAtOrDefault(i + j).Rating>=5 ? "color:orange" : "color:black")"></span>


                        </div>
                    </div>
                </div>
            }
        }
    </div>
}

PokeApp/Views/Pokemon/Index.cshtml
@model PokeApp.Models.Pokemon
<link href="~/css/PokeStyle.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class=>
    <div class="card opacity-75 justify-content-center">
        <h1 class="card-header ">Witamy w Poke swiecie! Oto @Model.Name</h1>
        <div class="card-body center">
            <button runat="server" class="arrows" onclick="changePokemon(0)">&larr;</button>
            <img class="image-style" src="@Model.Url" alt="Pokemon image source outdated :/" />
            <button class="arrows" onclick="changePokemon(1)"> &rarr;</button>
        </div>
        <div class="rating-container card-footer ">
           
            
                <div class=" image">
                    <asp:Button runat="server" id="st1" onmouseover="hoverRating(1)" onmouseout="actualRating()" onclick="updateRating(1)" class="fa fa-star star"></asp:Button>
                    <asp:Button runat="server" id="st2" onmouseover="hoverRating(2)" onmouseout="actualRating()" onclick="updateRating(2)" class="fa fa-star star"></asp:Button>
                    <asp:Button runat="server" id="st3" onmouseover="hoverRating(3)" onmouseout="actualRating()" onclick="updateRating(3)" class="fa fa-star star"></asp:Button>
                    <asp:Button runat="server" id="st4" onmouseover="hoverRating(4)" onmouseout="actualRating()" onclick="updateRating(4)" class="fa fa-star star"></asp:Button>
                    <asp:Button runat="server" id="st5" onmouseover="hoverRating(5)" onmouseout="actualRating()" onclick="updateRating(5)" class="fa fa-star star"></asp:Button>
                </div>
            

        </div>

    </div>
</div>


<script>
    const stars = [document.getElementById("st1"),document.getElementById("st2"),document.getElementById("st3"),document.getElementById("st4"),document.getElementById("st5")];
    function hoverRating(hoveredStar){
        let checked =stars.slice(0,hoveredStar)
        let unchecked =stars.slice(hoveredStar,6)
        checked.forEach((i)=>i.style.color="orange")
        unchecked.forEach((i)=>i.style.color="black")
    }

    function actualRating(){
        let checked =stars.slice(0,@Model.Rating)
        let unchecked =stars.slice(@Model.Rating,6)
        checked.forEach((i)=>i.style.color="orange")
        unchecked.forEach((i)=>i.style.color="black")
    }
     actualRating()
    function updateRating(Number) {
        $.ajax({
            url: '/Pokemon/UpdatePokemon',
            type: 'PUT',
             data: { argument: Number ,pokeid:@Model.PokemonId},
            success: function (result) {
                location.reload();
                actualRating()
            },
            error: function (xhr, status, error) {
                alert("failure")
            }
        });
    }
    function changePokemon(Next) {
        $.ajax({
            url: '/Pokemon/GetPokemon',
            type: 'GET',
             data: { next: Next ,pokeid:@Model.PokemonId},
            success: function (result) {
               location.reload();
               actualRating()
            },
            error: function (xhr, status, error) {
                alert("failure")
            }
        });
    }


</script>

PokeApp/Views/Pokemon/Pokedle.cshtml
@model Pokemon
<link href="~/css/PokeStyle.css" rel="stylesheet" type="text/css" />
<h4 class="text-white">Whos that pokemon?</h4>
<div class="card">
    <div class="card-header align-content-center mt-22">
        <h1 class="text-center fw-bolder " id=hiddenName>
            @String.Concat(Enumerable.Repeat("_ ", Model.Name.Length))
        </h1>

    </div>
    <div class="card-body center justify-content-center">
        <img id="pokemon" src="@Model.Url" id="MysteriousPokemon" class="noHover image-style guess-img" />
    </div>
    <div class="card-footer guess-input">
        <div class="d-flex flex-row w-75 justify-content-center">
            <input class="form-control w-50" type="text" placeholder="pokemon name" id="name" />
            <button class="btn btn-success" onclick="guess()">Make a guess</button>
        </div>
        <div class="d-flex flex-row align-items-center w-50 justify-content-around ">
            <span class=" border-0 justify-self-center mt-3" id="tries">You have tried 0 times</span>
            <button class="btn btn-secondary justify-self-center mt-3" onclick="tip()">Need a tip?</button>
        </div>

    </div>
</div>

<script>
    var numberOfTries=0;
    const name= document.getElementById("name")
    var unnknownLetters=Array.from(new Set("@Model.Name".split('')));
    var knownLetters=Array();
    var letterIndexes=Array.from(Array(unnknownLetters.length).keys())
    function LoadedProperly(){
        if(!document.getElementById("MysteriousPokemon").complete){
            location.reload();

        }

    }
    function guess(){

        if(name.value=="@Model.Name"){
            //alert("Congratulations!!!")
            document.getElementById("pokemon").classList.add("correct-choice")
            document.getElementById("pokemon").classList.remove("guess-img")
            document.getElementById("hiddenName").innerHTML="@Model.Name"
        }
        else{
            document.getElementById("pokemon").classList.add("wrong-choice")
            setTimeout(function(){document.getElementById("pokemon").classList.remove("wrong-choice")},1000)

            numberOfTries+=1;
            document.getElementById("tries").innerHTML="You have tried "+ numberOfTries + " times"
        }
    }

    function tip(){
        let randomLetter = unnknownLetters[Math.floor(Math.random() * unnknownLetters.length)];
        const index = unnknownLetters.indexOf(randomLetter);
        if (index > -1) { // only splice array when item is found
          unnknownLetters.splice(index, 1); // 2nd parameter means remove one item only
        }
     
        knownLetters.push(randomLetter);
        var resulting_string="";
      
        for(var i =0;i<"@Model.Name".length;i++){
            
            if(knownLetters.includes("@Model.Name".charAt(i))){
                resulting_string+="@Model.Name ".charAt(i);
            }
            else{
                resulting_string+="_ "
            }
        }
        if(unnknownLetters.length==0){
            alert("Tym razem sie nie udalo, pokemon to " + "@Model.Name" );
            location.reload()
        }
        document.getElementById("hiddenName").innerHTML=resulting_string;
      
    }

</script>

PokeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PokeApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PokeApp.styles.css" asp-append-version="true" />
    <link href="~/css/PokeStyle.css" rel="stylesheet" type="text/css" />
</head>
<body class="background">

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-secondary border-bottom box-shadow mb-3 bg-opacity-25">
            <div class="container-fluid">
                <a class="navbar-brand text-info" asp-area="" asp-controller="Pokemon" asp-action="Index">PokeApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="Pokemon" asp-action="Pokedle">Pokedle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="Pokemon" asp-action="Gallery">Gallery</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-info bg-secondary">
        <div class="container">
            &copy; 2023 - PokeApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>